
title: 'nova-explorer.github.io'
description: "Invitation to Cyberpunk Red."
# baseurl: "/jekyll-theme-console-demo-hacker"
url: "https://nova-explorer.github.io"

header_pages:
  - index.md
  - game.md
  - world.md
  - char.md
  - rules.md

style: hacker
remote_theme: b2a3e8/jekyll-theme-console

